services:
  authweb:
    image: ${DOCKER_REGISTRY-}authweb
    build:
      context: .
      dockerfile: WebApplication1/Dockerfile
    depends_on:
      - db

  db:
    image: postgres:15-alpine
    container_name: db
    hostname: database_host
    expose:
      - 5432
    environment:
      POSTGRES_USER: appuser
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: UserDb
    volumes:
      - db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d UserDb"]
      interval: 30s
      timeout: 10s
      retries: 3
volumes:
  db_data:
    name: db_data
