services:
  authweb:
    image: ${DOCKER_REGISTRY-}authweb
    build:
      context: .
      dockerfile: WebApplication1/Dockerfile
    ports:
      - "2280:8080"
    depends_on:
      - db

  coreweb:
    image: ${DOCKER_REGISTRY-}coreweb
    build:
      context: .
      dockerfile: Core.Web/Dockerfile
    ports:
      - "2281:8080"
    depends_on:
      - db

  db:
    image: postgres:15-alpine
    container_name: db
    hostname: database_host
    ports:
      - "1488:5432"
    expose:
      - 5432
    environment:
      POSTGRES_USER: appuser
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: UserDb
    volumes:
      - db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d UserDb"]
      interval: 30s
      timeout: 10s
      retries: 3

  rabbitmq:                      
    image: rabbitmq:3-management
    container_name: rabbitmq
    hostname: rabbitmq
    ports:
      - "5672:5672"  
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "ping"]
      interval: 30s
      timeout: 10s
      retries: 3

volumes:
  db_data:
    name: db_data
  rabbitmq_data:
    name: rabbitmq_data
